project:
  type: website
  output-dir: docs

website:
  title: "Matěj Tvarůžka"
  description: "Ecology & Spatial Data Science"
  
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/matejtvar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: github  # Automatically switches between light/dark code colors
    css: styles.css
    toc: true
    page-footer: 
      left: "© 2026 Matěj Tvarůžka"
      right: "Built with Quarto"