project:
  type: website
  output-dir: docs

website:
  title: "Matěj Tvarůžka"
  description: "Ecology & Spatial Data Science"

  page-footer: 
    left: "© 2026 Matěj Tvarůžka"
    right: "Built with Quarto"

  navbar:
    background: "#2E2252"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/matejtvar
      - icon: google
        href: https://scholar.google.com/citations?view_op=list_works&hl=cs&hl=cs&user=6z0qsfMAAAAJ
        aria-label: Google Scholar
      - icon: envelope
        href: mailto:matej.tvar@gmail.com
      - icon: binoculars
        href: https://ebird.org/profile/MTQwNTM2Mw
        aria-label: eBird

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: github
    toc: true